# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginPage_Udemy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginPage_Udemy
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'JGProgressHUD','~>2.0.3'
    pod 'GoogleSignIn'
    pod 'Firebase/Database'
    pod 'paper-onboarding'
end
